be:
  sorondare:
    greeting:
      format: Hello %s
      default-name: Me

quarkus:
  datasource:
    db-kind: h2
    username: sa
    password:
    jdbc:
      url: jdbc:h2:mem:quarkus-test-database;INIT=CREATE SCHEMA IF NOT EXISTS quarkus
    metrics:
      enabled: true

  liquibase:
    change-log: db/changelog-master.yml
    migrate-at-start: true
    default-schema-name: quarkus

  hibernate-orm:
    database:
      default-schema: quarkus

  security:
    users:
      file:
        enabled: true
        users: users.properties
        roles: roles.properties
        realm-name: QuarkusTest
        plain-text: false

  log:
    level: INFO
