// default greeting
GET http://localhost:8080/greeting/hello?name=Me
Accept: text/plain
Authorization: Basic {{username}} {{password}}

###

// default greeting without authentication
GET http://localhost:8080/greeting/hello?name=Me
Accept: text/plain

> {%
    client.test("Test failed authentication", function() {
        client.assert(response.status === 401, "Response status is not 401");
    });
%}

###

// default greeting with admin account
GET http://localhost:8080/greeting/hello
Accept: text/plain
Authorization: Basic {{adminUsername}} {{adminPassword}}

###

// All formats
GET http://localhost:8080/greeting/format
Accept: application/json
Authorization: Basic {{adminUsername}} {{adminPassword}}

###

// New empty format
POST http://localhost:8080/greeting/format
Content-Type: application/json
Authorization: Basic {{adminUsername}} {{adminPassword}}

{
  "format": null,
  "name": ""
}

> {%
    client.test("Request returns error", function() {
        client.assert(response.status === 400, "Response status is not 400");
    });
%}

###

// New format
POST http://localhost:8080/greeting/format
Content-Type: application/json
Authorization: Basic {{adminUsername}} {{adminPassword}}

{
  "format": "Voici mon format pour %s",
  "name": "new_test_request_format"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 201, "Response status is not 200");
    });

    client.global.set('formatId', response.body.id);
    client.global.set('formatName', response.body.name);
%}

###

// Get created format by id
GET http://localhost:8080/greeting/format/{{formatId}}
Accept: application/json
Authorization: Basic {{adminUsername}} {{adminPassword}}

###

// Get created format by name
GET http://localhost:8080/greeting/format/search?formatName={{formatName}}
Accept: application/json
Authorization: Basic {{adminUsername}} {{adminPassword}}

###

// Get greeting with new format
GET http://localhost:8080/greeting/hello?name={{name}}&formatName={{formatName}}
Accept: text/plain
Authorization: Basic {{username}} {{password}}

###

// Update created format
PUT http://localhost:8080/greeting/format/{{formatId}}
Content-Type: application/json
Authorization: Basic {{adminUsername}} {{adminPassword}}

{
  "name": "{{formatName}}",
  "format": "Nouveau format pour %s"
}

###

// Delete the created format
DELETE http://localhost:8080/greeting/format/{{formatId}}
Authorization: Basic {{adminUsername}} {{adminPassword}}
