// default greeting
GET http://localhost:8080/greeting/hello?name=Me
Accept: text/plain
Authorization: Basic {{username}} {{password}}

###

// default greeting without authentication
GET http://localhost:8080/greeting/hello?name=Me
Accept: text/plain

> {%
    client.test("Test failed authentication", function() {
        client.assert(response.status === 401, "Response status is not 401");
    });
%}

###

// default greeting with admin account
GET http://localhost:8080/greeting/hello
Accept: text/plain
Authorization: Basic {{adminUsername}} {{adminPassword}}

###

// All formats
GET http://localhost:8080/greeting/format
Accept: application/json
Authorization: Basic {{adminUsername}} {{adminPassword}}

###

// New empty format
POST http://localhost:8080/greeting/format
Content-Type: application/json
Authorization: Basic {{adminUsername}} {{adminPassword}}

{
  "format": null
}

> {%
    client.test("Request returns error", function() {
        client.assert(response.status === 400, "Response status is not 400");
    });
%}

###

// New format
POST http://localhost:8080/greeting/format
Content-Type: application/json
Authorization: Basic {{adminUsername}} {{adminPassword}}

{
  "format": "Voici mon format pour %s"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
        client.global.set('formatId', response.body.id);
    });
%}

###

// Get created format
GET http://localhost:8080/greeting/hello?name={{name}}&formatId={{formatId}}
Accept: text/plain
Authorization: Basic {{username}} {{password}}

###

// Update created format
PUT http://localhost:8080/greeting/format/{{formatId}}
Content-Type: application/json
Authorization: Basic {{adminUsername}} {{adminPassword}}

{
  "format": "Nouveau format pour %s"
}

###

// Delete the created format
DELETE http://localhost:8080/greeting/format/{{formatId}}
Authorization: Basic {{adminUsername}} {{adminPassword}}
